name: flutterfire_ui
description: UI library built on top of firebase services
version: 0.4.0+5
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/flutterfire_ui
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/flutterfire_ui

false_secrets:
  - example/**

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  cloud_firestore: ^3.1.14
  collection: ^1.15.0
  email_validator: ^2.0.1
  firebase_auth: ^3.3.17
  firebase_core: ^1.10.2
  firebase_database: ^9.0.13
  firebase_dynamic_links: ^4.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.0
  flutterfire_ui_oauth: ^0.1.0

dev_dependencies:
  firebase_auth_mocks: ^0.8.4
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: SocialIcons
      fonts:
        - asset: assets/fonts/SocialIcons.ttf
  assets:
    - assets/countries.json
